/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gd_deepsec_nativeencyption_NdkJNIUtils */

#ifndef _Included_com_gd_deepsec_nativeencyption_NdkJNIUtils
#define _Included_com_gd_deepsec_nativeencyption_NdkJNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gd_deepsec_nativeencyption_NdkJNIUtils
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gd_deepsec_nativeencyption_NdkJNIUtils_hello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
